.\" 
.TH "ebotula.conf" "5" "5 August 2003" "" ""
.SH "NAME"
ebotula.conf \- Configuration file for IRC bot ebotula
.SH "DESCRIPTION"
.I ebotula.conf
is the configuration file for the IRC bot 
.IR ebotula(1) .
It is usally placed in /etc. If you want to use another configuration
file, you can do so by giving ebotula the parameter -f <name_of_conf_file>
when you start it. In ebotula.conf the default values of the parameters
for ebotula are set. Any command line paramter will overwrite the value
taken from this config file.
.SH FILES
/etc/ebotula.conf
.SH "SEE ALSO"
ebotula(1)
.SH "AUTHORS"
Steffen Laube <realebula@gmx.de>,
Thomas Stein <linux@tstein.net>
.SH VERSION
0.1
