.TH EBOTULA 1 "07 March 03"
.SH NAME
ebotula \-  IRC bot
.SH SYNOPSIS
\fBebotula\fP [ options ]
.SH DESCRIBTION
\fIebotula\fP is a irc bot for general task in one or more channels.
.SS Options
.TP
\fB-h, -?\fP
show the help text and exit
.TP
\fB-v\fP
show the version and exit
.TP
\fB-m\fP
enable the dialog for creating a new master
.SH FILES
ebotula, ebotula.conf
.SH "SEE ALSO"
RFC1459, RFC2810, RFC2811, RFC2812
.SH AUTHOR
Steffen Laube <realebula@gmx.de>
.SH VERSION
v0.1.1b-dev
.SH BUGS

