#ifndef IRCHELP_H
#define IRCHELP_H

#define HELP_ITEM_SIZE	10

#ifndef		EOM
	#define	EOM		"."
#endif

static const char *irchelp_msg[]={
	"This is the  help system of the using  this bot.",
	"!help COMMAND for information to a spezial command",
	"------------------------------------------------------------------------",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	
	"!help",
	"give general help for using this bot",
	"!help                -> command list",
	"!help COMMAND        -> information about this command",
	"",
	"",
	"",
	"",
	"",
	"",
	
	"!version",
	"print the version information",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	
	"!ident",
	"identify by the bot to using the other commands",
	"You must have at account to using this command!(see !hello)",
	"!ident LOGIN PASS    -> identify by the bot with password",
	"!ident LOGIN         -> identify by the bot with epmty password",
	"",
 	"",
	"",
	"",
	"",
	
	"!logoff",
	"log off by the  bot.",
	"You must have identified",
	"",
	"",
	"",
 	"",
	"",
	"",
	"",
	
	"!die",
	"stop the execution of the bot.",
	"Only the bot master can use this command.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	
	"!hello",
	"create a new account.",
	"Any user can use this to creating a account",
	"The login of  this new account is the current nick",
	"",
	"",
	"",
	"",
	"",
	"",

	"!nick",
	"change the nickname of the bot",
	"Only the bot master can use this command.",
	"!nick NICKNAME       -> set the new nickname",
	"",
	"",
	"",
	"",
	"",
	"",

	"!addchannel",
	"the bot join and add a new channel",
	"Only the bot master can use this command.",
	"!addchannel #CHANNEL ->Add and join this channel",
	"",
	"",
	"",
	"",
	"",											  
	"",

	"!rmchannel",
	"the bot part and remove a old channel",
	"Only the bot master can use this command.",
	"!rmchannel #CHANNEL  ->Remove and part this channel",
	"",
	"",
	"",
	"",
	"",
	"",

	"!join",
	"the bot  join a new channel",
	"Only the bot master can use this command.",
	"!join #CHANNEL       ->Join this channel",
	"",
	"",
	"",
	"",
	"",
	"",

	"!part",
	"the bot part a channel",
	"Only the bot master can use this command.",
	"!part #CHANNEL       ->Part this channel",
	"",
	"",
	"",
	"",
	"",
	"",

	"!pass",
	"change the password for the account",
	"!pass PASSWORD       ->Set a new password",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	
	"!channels",
	"Print out a list of all Channels from the bot",
	"Only the bot master can use this command.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	
	// end mark of the complet array
	"."

	"!KOMMAND",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
};

#endif
